#!/usr/bin/env python3
"""Generate src/font_data.h - ASCII bitmap atlas from a TTF.

The C++ port has no font rasterizer, so the atlas is baked here with PIL
once and committed. Run from cpp_port/:

    python3 tools/gen_font.py
"""

from __future__ import annotations

import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FIRST = 32
LAST = 126
COUNT = LAST - FIRST + 1
COLS = 16
CELL_W = 24
CELL_H = 32
PIXEL_SIZE = 26

ROOT = Path(__file__).resolve().parents[2]
FONT_CANDIDATES = [
    ROOT / "assets/images/assest/Roboto-Bold.ttf",
    ROOT / "assets/images/assest/Roboto-Regular.ttf",
]


def main() -> None:
    font_path = next((p for p in FONT_CANDIDATES if p.is_file()), None)
    if font_path is None:
        raise SystemExit("no TTF font found")
    font = ImageFont.truetype(str(font_path), PIXEL_SIZE)

    rows = (COUNT + COLS - 1) // COLS
    width = COLS * CELL_W
    height = rows * CELL_H
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)

    advances: list[int] = []
    for i in range(COUNT):
        ch = chr(FIRST + i)
        col = i % COLS
        row = i // COLS
        x = col * CELL_W
        y = row * CELL_H
        # center the glyph in the cell (baseline at CELL_H - 6)
        bbox = draw.textbbox((0, 0), ch, font=font)
        gw = bbox[2] - bbox[0]
        xoff = (CELL_W - gw) // 2 - bbox[0]
        yoff = CELL_H - 6 - bbox[3]
        draw.text((x + xoff, y + yoff), ch, fill=255, font=font)
        advances.append(max(1, int(round(draw.textlength(ch, font=font)))))

    pixels = image.load()
    data = bytearray()
    for y in range(height):
        for x in range(width):
            data.append(pixels[x, y])

    out = Path(__file__).resolve().parents[1] / "src/font_data.h"
    with out.open("w") as f:
        f.write("// generated by tools/gen_font.py - do not edit\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write("namespace bw {\n")
        f.write(f"constexpr int kFontFirst = {FIRST};\n")
        f.write(f"constexpr int kFontCount = {COUNT};\n")
        f.write(f"constexpr int kFontCols = {COLS};\n")
        f.write(f"constexpr int kFontCellW = {CELL_W};\n")
        f.write(f"constexpr int kFontCellH = {CELL_H};\n")
        f.write(f"constexpr int kFontAtlasW = {width};\n")
        f.write(f"constexpr int kFontAtlasH = {height};\n")
        f.write("constexpr unsigned char kFontAtlas[] = {\n")
        for i in range(0, len(data), 24):
            chunk = data[i : i + 24]
            f.write("    " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n")
        f.write("constexpr unsigned char kFontAdvance[kFontCount] = {\n    ")
        f.write(",".join(str(a) for a in advances))
        f.write("\n};\n")
        f.write("} // namespace bw\n")
    print(f"wrote {out} ({width}x{height}, {len(data)} bytes)")


if __name__ == "__main__":
    main()
